"""Added residential homes table

Revision ID: 05daf92d23ce
Revises: 
Create Date: 2025-06-28 14:22:01.233251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05daf92d23ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residential_homes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sqm', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('receptions', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.Column('incode', sa.String(), nullable=False),
    sa.Column('outcode', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('crime_anti_social', sa.Integer(), nullable=False),
    sa.Column('crime_theft', sa.Integer(), nullable=False),
    sa.Column('crime_burglary', sa.Integer(), nullable=False),
    sa.Column('crime_criminal_damage', sa.Integer(), nullable=False),
    sa.Column('crime_drugs', sa.Integer(), nullable=False),
    sa.Column('crime_weapon_possession', sa.Integer(), nullable=False),
    sa.Column('crime_public_order', sa.Integer(), nullable=False),
    sa.Column('crime_robbery', sa.Integer(), nullable=False),
    sa.Column('crime_vehicle', sa.Integer(), nullable=False),
    sa.Column('crime_other', sa.Integer(), nullable=False),
    sa.Column('num_pois', sa.Integer(), nullable=False),
    sa.Column('num_schools', sa.Integer(), nullable=False),
    sa.Column('avg_distance_all', sa.Float(), nullable=False),
    sa.Column('min_distance_school', sa.Float(), nullable=False),
    sa.Column('sqm_per_bed', sa.Float(), nullable=False),
    sa.Column('sqm_per_room', sa.Float(), nullable=False),
    sa.Column('regional_avg_price', sa.Float(), nullable=False),
    sa.Column('price_per_sqm', sa.Float(), nullable=False),
    sa.Column('regional_avg_price_per_sqm', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('tenure', sa.String(), nullable=False),
    sa.Column('epc_rating', sa.String(), nullable=False),
    sa.Column('sold_date', sa.String(), nullable=False),
    sa.Column('sold_price', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residential_homes')
    # ### end Alembic commands ###
