"""Added address fields to residential homes table

Revision ID: 7fc82e9bd636
Revises: 05daf92d23ce
Create Date: 2025-06-28 14:26:29.390530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc82e9bd636'
down_revision: Union[str, None] = '05daf92d23ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_homes', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residential_homes', 'address')
    # ### end Alembic commands ###
