"""Added uprn to residential homes table

Revision ID: 9879683aa6d7
Revises: 9f93c972dbae
Create Date: 2025-06-28 14:58:50.296191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9879683aa6d7'
down_revision: Union[str, None] = '9f93c972dbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_homes', sa.Column('uprn', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'residential_homes', ['uprn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residential_homes', type_='unique')
    op.drop_column('residential_homes', 'uprn')
    # ### end Alembic commands ###
