"""Added crime_violence to residential homes table

Revision ID: 9f93c972dbae
Revises: 7fc82e9bd636
Create Date: 2025-06-28 14:31:04.480461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f93c972dbae'
down_revision: Union[str, None] = '7fc82e9bd636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residential_homes', sa.Column('crime_violence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residential_homes', 'crime_violence')
    # ### end Alembic commands ###
